import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider, TokenProvider } from '@/components/Providers'
import Navbar from '@/components/Navbar'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const dynamic = 'force-dynamic'

export default async function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode
  modal: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <TokenProvider>
        <body
          className={`${inter.className} min-h-screen pt-12 antialiased dark:bg-gradient-to-b dark:from-slate-900 dark:to-slate-950`}>
          <ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
            <Navbar />
            <div className='container mx-auto h-full max-w-7xl pt-6'>
              {modal}
              {children}
            </div>
            <Toaster />
          </ThemeProvider>
        </body>
      </TokenProvider>
    </html>
  )
}
