import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider, TokenProvider } from '@/components/Providers'
import Navbar from '@/components/Navbar'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode
  authModal: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <TokenProvider>
        <body className={`${inter.className} min-h-screen pt-12 antialiased`}>
          <ThemeProvider attribute='class' defaultTheme='light' enableSystem>
            <Navbar />
            <div className='container mx-auto h-full max-w-7xl pt-12'>
              {authModal}
              {children}
            </div>
            <Toaster />
          </ThemeProvider>
        </body>
      </TokenProvider>
    </html>
  )
}
